loss_paths:
- "/media/cs533r/data_b/zhijie/AB_test_nips/affine_tests/losses/full_model.csv"
- "/media/cs533r/data_b/zhijie/AB_test_nips/affine_tests/losses/no_scale.csv"

exp_names:
- "Full LS Layer"
- "LS Layer: No Affine Transforms"

width: 1300
height: 1400

max_num_steps: 50001

loss_min: 0.012
loss_max: 0.016

smooth: 0.5

show_labels: False

legend_location: "upper right"