loss_paths:
- "/media/cs533r/data_b/zhijie/AB_test_nips/pri_num/losses/1_25088.csv"
- "/media/cs533r/data_b/zhijie/AB_test_nips/pri_num/losses/2_21600.csv"
- "/media/cs533r/data_b/zhijie/AB_test_nips/pri_num/losses/3_13400.csv"
- "/media/cs533r/data_b/zhijie/AB_test_nips/pri_num/losses/4_5000.csv"
- "/media/cs533r/data_b/zhijie/AB_test_nips/pri_num/losses/5_1536.csv"

exp_names:
- "25000"
- "22000"
- "13000"
- "5000"
- "1300"

width: 1200
height: 1200

max_num_steps: 50001

loss_min: 0.02
loss_max: 0.05

smooth: 0.5

show_labels: False

legend_location: "lower left"