"img_path": "/home/eric/cpsc533r/project/utils/visualization/sse_diagram/snapshot_armadillo.png"

"shape_name": "armadillo"

"size": -1

"bin_r": 95
"bin_g": 137
"bin_b": 210

"neighborhood_size": 5

"show_title": False