mesh_in_paths:
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_airplane/airplane.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_armadillo/armadillo.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_asian_dragon/asian_dragon.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_at-ot/at-ot.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_bimba/bimba.ply"
- "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_beard_man/beard_man.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_camera/camera.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_cathedral/cathedral.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_david/david.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_dragon/dragon.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_dragon_warrior/dragon_warrior.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_engine/engine.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_gear_shift/gear_shift.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_guangong/guangong.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_lion/lion.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_lunar_lander/lunar_lander.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_ninjago_city/ninjago_city.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_oak_tree/oak_tree.ply"
# - "/home/eric/cpsc533r/project/instant-ngp/workspace/2022_07_15/default_thai_statue/thai_statue.ply"

mesh_out_paths:
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/airplane.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/armadillo.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/asian_dragon.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/at-ot.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/bimba.ply"
- "/media/cs533r/data_b/instant-ngp_results/3d/default/beard_man.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/camera.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/cathedral.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/david.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/dragon.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/dragon_warrior.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/engine.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/gear_shift.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/guangong.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/lion.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/lunar_lander.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/ninjago_city.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/oak_tree.ply"
# - "/media/cs533r/data_b/instant-ngp_results/3d/default/thai_statue.ply"
