mesh_in_paths:
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_armadillo/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_asian_dragon/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_at-ot/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_beard_man/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_camera/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_david/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_dragon/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_dragon_warrior/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_engine/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_gear_shift/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_guangong/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_lion/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_lunar_lander/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_ninjago_city/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_oak_tree/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/4_hidden_layers_thai_statue/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_armadillo/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_asian_dragon/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_at-ot/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_beard_man/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_camera/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_david/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_dragon/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_dragon_warrior/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_engine/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_gear_shift/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_guangong/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_lion/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_lunar_lander/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_ninjago_city/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_oak_tree/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/5_hidden_layers_thai_statue/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_armadillo/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_asian_dragon/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_at-ot/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_beard_man/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_camera/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_david/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_dragon/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_dragon_warrior/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_engine/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_gear_shift/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_guangong/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_lion/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_lunar_lander/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_ninjago_city/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_oak_tree/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/6_hidden_layers_thai_statue/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_armadillo/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_asian_dragon/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_at-ot/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_beard_man/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_camera/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_david/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_dragon/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_dragon_warrior/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_engine/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_gear_shift/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_guangong/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_lion/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_lunar_lander/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_ninjago_city/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_oak_tree/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/7_hidden_layers_thai_statue/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_armadillo/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_asian_dragon/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_at-ot/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_beard_man/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_camera/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_david/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_dragon/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_dragon_warrior/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_engine/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_gear_shift/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_guangong/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_lion/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_lunar_lander/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_ninjago_city/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_oak_tree/test.ply"
- "/media/eric/data_a/cpsc533r/siren_results+trained_models/2022_07_17/8_hidden_layers_thai_statue/test.ply"

mesh_out_paths:
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/armadillo.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/asian_dragon.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/at-ot.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/beard_man.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/camera.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/david.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/dragon.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/dragon_warrior.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/engine.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/gear_shift.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/guangong.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/lion.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/lunar_lander.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/ninjago_city.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/oak_tree.ply"
- "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/thai_statue.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/armadillo.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/asian_dragon.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/at-ot.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/beard_man.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/camera.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/david.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/dragon.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/dragon_warrior.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/engine.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/gear_shift.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/guangong.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/lion.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/lunar_lander.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/ninjago_city.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/oak_tree.ply"
- "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/thai_statue.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/armadillo.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/asian_dragon.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/at-ot.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/beard_man.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/camera.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/david.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/dragon.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/dragon_warrior.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/engine.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/gear_shift.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/guangong.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/lion.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/lunar_lander.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/ninjago_city.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/oak_tree.ply"
- "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/thai_statue.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/armadillo.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/asian_dragon.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/at-ot.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/beard_man.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/camera.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/david.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/dragon.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/dragon_warrior.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/engine.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/gear_shift.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/guangong.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/lion.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/lunar_lander.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/ninjago_city.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/oak_tree.ply"
- "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/thai_statue.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/armadillo.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/asian_dragon.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/at-ot.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/beard_man.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/camera.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/david.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/dragon.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/dragon_warrior.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/engine.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/gear_shift.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/guangong.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/lion.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/lunar_lander.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/ninjago_city.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/oak_tree.ply"
- "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/thai_statue.ply"
