mesh_in_paths:
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_armadillo/results/armadillo_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_asian_dragon/results/asian_dragon_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_at-ot/results/at-ot_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_beard_man/results/beard_man_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_bimba/results/bimba_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_camera/results/camera_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_cathedral/results/cathedral_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_david/results/david_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_dragon/results/dragon_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_dragon_warrior/results/dragon_warrior_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_engine/results/engine_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_gear_shift/results/gear_shift_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_guangong/results/guangong_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_lion/results/lion_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_lunar_lander/results/lunar_lander_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_ninjago_city/results/ninjago_city_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_oak_tree/results/oak_tree_512.ply"
- "/media/eric/data_a/cpsc533r/torch-ngp_results+trained_models/workspace/default_thai_statue/results/thai_statue_512.ply"

mesh_out_paths:
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/armadillo.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/asian_dragon.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/at-ot.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/beard_man.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/bimba.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/camera.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/cathedral.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/david.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/dragon.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/dragon_warrior.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/engine.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/gear_shift.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/guangong.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/lion.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/lunar_lander.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/ninjago_city.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/oak_tree.ply"
- "/media/cs533r/data_b/torch-ngp_results/3d/default/512/thai_statue.ply"