mesh_paths:
- "/media/cs533r/data_b/normalized_GT_3D_shapes/obj/armadillo.obj"
- "/media/cs533r/data_b/533R_results_1/3d_shapes/instantngp/armadillo_base.obj"
- "/media/cs533r/data_b/533R_results_1/3d_shapes/ldif/armadillo.ply"

experiment_name: "test"

normalize: True

# chamfer
metric: "l2"
num_points_to_sample: 100000
square_distances: False

# f-score
cube_side_length: 1.0
cube_side_factor: 2000

# metro
num_samples: 100000

# iou
scale: 1