gt_mesh_paths:
- "/media/cs533r/data_b/data/3d/obj/armadillo.obj"
- "/media/cs533r/data_b/data/3d/obj/asian_dragon.obj"
- "/media/cs533r/data_b/data/3d/obj/at-ot.obj"
- "/media/cs533r/data_b/data/3d/obj/beard_man.obj"
- "/media/cs533r/data_b/data/3d/obj/bimba.obj"
- "/media/cs533r/data_b/data/3d/obj/camera.obj"
- "/media/cs533r/data_b/data/3d/obj/cathedral.obj"
- "/media/cs533r/data_b/data/3d/obj/david.obj"
- "/media/cs533r/data_b/data/3d/obj/dragon.obj"
- "/media/cs533r/data_b/data/3d/obj/dragon_warrior.obj"
- "/media/cs533r/data_b/data/3d/obj/engine.obj"
- "/media/cs533r/data_b/data/3d/obj/gear_shift.obj"
- "/media/cs533r/data_b/data/3d/obj/guangong.obj"
- "/media/cs533r/data_b/data/3d/obj/lion.obj"
- "/media/cs533r/data_b/data/3d/obj/lunar_lander.obj"
- "/media/cs533r/data_b/data/3d/obj/ninjago_city.obj"
- "/media/cs533r/data_b/data/3d/obj/oak_tree.obj"
- "/media/cs533r/data_b/data/3d/obj/thai_statue.obj"

pred_mesh_paths:
  torch-ngp:
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/armadillo.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/asian_dragon.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/at-ot.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/beard_man.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/bimba.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/camera.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/cathedral.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/david.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/dragon.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/dragon_warrior.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/engine.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/gear_shift.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/guangong.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/lion.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/lunar_lander.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/ninjago_city.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/oak_tree.ply"
  - "/media/cs533r/data_b/torch-ngp_results/3d/default/512/thai_statue.ply"

experiment_name: "512_torch-ngp_jul21"

metric: "l2"

normalize: False

num_points_to_sample: 100000

square_distances: False