gt_mesh_paths:
- "/media/cs533r/data_b/data/3d/obj/armadillo.obj"
- "/media/cs533r/data_b/data/3d/obj/asian_dragon.obj"
- "/media/cs533r/data_b/data/3d/obj/at-ot.obj"
- "/media/cs533r/data_b/data/3d/obj/beard_man.obj"
- "/media/cs533r/data_b/data/3d/obj/camera.obj"
- "/media/cs533r/data_b/data/3d/obj/cathedral.obj"
- "/media/cs533r/data_b/data/3d/obj/david.obj"
- "/media/cs533r/data_b/data/3d/obj/dragon.obj"
- "/media/cs533r/data_b/data/3d/obj/dragon_warrior.obj"
- "/media/cs533r/data_b/data/3d/obj/engine.obj"
- "/media/cs533r/data_b/data/3d/obj/gear_shift.obj"
- "/media/cs533r/data_b/data/3d/obj/guangong.obj"
- "/media/cs533r/data_b/data/3d/obj/lion.obj"
- "/media/cs533r/data_b/data/3d/obj/lunar_lander.obj"
- "/media/cs533r/data_b/data/3d/obj/ninjago_city.obj"
- "/media/cs533r/data_b/data/3d/obj/oak_tree.obj"
- "/media/cs533r/data_b/data/3d/obj/thai_statue.obj"

pred_mesh_paths:
  bacon:
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/armadillo.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/asian_dragon.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/at-ot.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/beard_man.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/camera.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/cathedral.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/david.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/dragon.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/dragon_warrior.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/engine.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/gear_shift.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/guangong.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/lion.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/lunar_lander.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/ninjago_city.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/oak_tree.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/512/thai_statue.obj"
  siren_default:
  - "/media/cs533r/data_b/siren_results/3d/default/512/armadillo.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/asian_dragon.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/at-ot.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/beard_man.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/camera.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/cathedral.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/david.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/dragon.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/dragon_warrior.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/engine.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/gear_shift.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/guangong.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/lion.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/lunar_lander.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/ninjago_city.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/oak_tree.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/512/thai_statue.ply"
  siren_4_hidden_layers:
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/armadillo.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/asian_dragon.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/at-ot.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/beard_man.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/camera.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/cathedral.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/david.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/dragon.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/dragon_warrior.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/engine.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/gear_shift.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/guangong.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/lion.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/lunar_lander.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/ninjago_city.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/oak_tree.ply"
  - "/media/cs533r/data_b/siren_results/3d/4_hidden_layers/512/thai_statue.ply"
  siren_5_hidden_layers:
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/armadillo.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/asian_dragon.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/at-ot.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/beard_man.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/camera.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/cathedral.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/david.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/dragon.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/dragon_warrior.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/engine.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/gear_shift.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/guangong.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/lion.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/lunar_lander.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/ninjago_city.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/oak_tree.ply"
  - "/media/cs533r/data_b/siren_results/3d/5_hidden_layers/512/thai_statue.ply"
  siren_6_hidden_layers:
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/armadillo.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/asian_dragon.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/at-ot.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/beard_man.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/camera.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/cathedral.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/david.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/dragon.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/dragon_warrior.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/engine.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/gear_shift.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/guangong.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/lion.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/lunar_lander.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/ninjago_city.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/oak_tree.ply"
  - "/media/cs533r/data_b/siren_results/3d/6_hidden_layers/512/thai_statue.ply"
  siren_7_hidden_layers:
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/armadillo.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/asian_dragon.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/at-ot.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/beard_man.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/camera.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/cathedral.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/david.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/dragon.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/dragon_warrior.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/engine.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/gear_shift.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/guangong.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/lion.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/lunar_lander.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/ninjago_city.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/oak_tree.ply"
  - "/media/cs533r/data_b/siren_results/3d/7_hidden_layers/512/thai_statue.ply"
  siren_8_hidden_layers:
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/armadillo.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/asian_dragon.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/at-ot.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/beard_man.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/camera.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/cathedral.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/david.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/dragon.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/dragon_warrior.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/engine.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/gear_shift.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/guangong.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/lion.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/lunar_lander.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/ninjago_city.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/oak_tree.ply"
  - "/media/cs533r/data_b/siren_results/3d/8_hidden_layers/512/thai_statue.ply"
  instant-ngp:
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/armadillo.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/asian_dragon.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/at-ot.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/beard_man.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/camera.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/cathedral.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/david.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/dragon.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/dragon_warrior.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/engine.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/gear_shift.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/guangong.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/lion.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/lunar_lander.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/ninjago_city.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/oak_tree.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/512/thai_statue.ply"

experiment_name: "512_bacon+siren+instant-ngp_jul20"

metric: "l2"

normalize: True

num_points_to_sample: 100000

square_distances: False