mesh_paths:
- "/media/cs533r/data_b/normalized_GT_3D_shapes/obj/armadillo.obj"
- "/media/cs533r/data_b/533R_results_1/3d_shapes/instantngp/armadillo_base.obj"
- "/media/cs533r/data_b/533R_results_1/3d_shapes/ldif/armadillo.ply"

experiment_name: "test"

metric: "l2"

normalize: True

num_points_to_sample: 100000

square_distances: False