mesh_paths:
- "/media/cs533r/data_b/figures_and_tables/fig_3d_comparison/beard_man/normalized/gt.obj"
- "/media/cs533r/data_b/bacon_results/3d/outputs_multiscale_normalized_256/bacon_beard_man_multiscale_4.obj"
- "/media/cs533r/data_b/figures_and_tables/fig_3d_comparison/beard_man/normalized/sape_256.obj"
- "/media/cs533r/data_b/figures_and_tables/fig_3d_comparison/beard_man/normalized/siren_256.ply"

experiment_name: "test"

cube_side_length: 1.0

cube_side_factor: 500

normalize: True