mesh_paths:
- "/media/cs533r/data_b/figures_and_tables/fig_3d_comparison/bimba/bimba_gt_normalized.ply"
- "/media/cs533r/data_b/figures_and_tables/fig_3d_comparison/bimba/bimba_instantngp_normalized.ply"
- "/media/cs533r/data_b/figures_and_tables/fig_3d_comparison/bimba/bimba_lslayer_normalized.ply"

experiment_name: "test"

scale: 1

normalize: True