mesh_paths:
- "/media/cs533r/data_b/normalized_GT_3D_shapes/obj/beard_man.obj"
- "/media/cs533r/data_b/533R_results_1/3d_shapes/siren/beard_man.ply"
- "/media/cs533r/data_b/533R_results_1/3d_shapes/ldif/beard_man.ply"
- "/media/cs533r/data_b/533R_results_1/3d_shapes/FFN/beard_man_new.ply"
- "/media/cs533r/data_b/normalized_instantngp_3D_shapes/beard_man_instantngp_normalized.ply"
- "/media/cs533r/data_b/533R_results_1/3d_shapes/lslayer/beard_man_2022-05-18-04-18-34_1024_26000.ply"
- "/media/cs533r/data_b/533R_results_1/3d_shapes/sape/sape_beard_man_1024.ply"
- "/media/cs533r/data_b/533R_results_1/3d_shapes/bacon/bacon_beard_man_multiscale_4.obj"

experiment_name: "beard_man"

num_samples: 100000

normalize: True
