img_paths:
- "/media/cs533r/data_b/new_images/orszaghaz/orszaghaz.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/results/results_ngp/result_orszaghaz.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/results/results_freq/result_orszaghaz.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/lslayer_new/result_orszaghaz.jpg"

experiment_name: "orszaghaz_ngp+ffn+lslayer"

grayscale: False