gt_img_paths:
- "/media/cs533r/data_b/data/2d/copenhagen.jpg"
- "/media/cs533r/data_b/data/2d/hamburg.jpg"

pred_img_paths:
  bacon:
    - "/media/eric/data_a/cpsc533r/bacon_results+trained_models/2022_06_28/bacon_copenhagen_monoscale/summaries/imgs/im_100000.png"
    - "/media/eric/data_a/cpsc533r/bacon_results+trained_models/2022_06_28/bacon_hamburg_monoscale/summaries/imgs/im_100000.png"
  siren:
    - "/media/cs533r/data_b/siren_results/2d/copenhagen_pred_100000.png"
    - "/media/cs533r/data_b/siren_results/2d/hamburg_pred_100000.png"

experiment_name: "batch_test_rgb"

grayscales:
- False
- False