img_paths:
- "/media/cs533r/data_b/533R_results_1/2d_images/albert/reference.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/albert/instantngp_new.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/albert/FFN.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/albert/siren.png"
- "/media/cs533r/data_b/533R_results_1/2d_images/albert/lslayer_latest.jpg"

experiment_name: "albert_ngp+ffn+siren+lslayer"

grayscale: True