img_paths:
- "/media/cs533r/data_b/533R_results_1/2d_images/tokyo/reference.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/tokyo/instantngp_new.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/tokyo/ffn_new.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/tokyo/siren.png"
- "/media/cs533r/data_b/533R_results_1/2d_images/tokyo/ls-layer.jpg"

experiment_name: "tokyo_ngp+ffn+siren+lslayer"

grayscale: False