img_paths:
- "/media/cs533r/data_b/new_images/stonehenge/stonehenge.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/results/results_ngp/result_stonehenge.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/results/results_freq/result_stonehenge.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/results/results_lslayer/result_stonehenge.jpg"

experiment_name: "stonehenge_ngp+ffn+lslayer"

grayscale: False