img_paths:
- "/media/cs533r/data_b/new_images/matterhorn/matterhorn.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/results/results_ngp/result_matterhorn.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/results/results_freq/result_matterhorn.jpg"
- "/media/cs533r/data_b/533R_results_1/2d_images/lslayer_new/result_matterhorn.jpg"

experiment_name: "matterhorn_ngp+ffn+lslayer"

grayscale: False