gt_img_paths:
- "/media/cs533r/data_b/533R_results_1/2d_images/albert/reference.jpg"
- "/media/cs533r/data_b/data/2d/hamburg.jpg"

pred_img_paths:
- "/media/cs533r/data_b/533R_results_1/2d_images/albert/sape_albert_4k.png"
- "/media/eric/data_a/cpsc533r/bacon_results+trained_models/2022_06_28/bacon_hamburg_monoscale/summaries/imgs/im_100000.png"

experiment_name: "batch_test_grayscale"

grayscales:
- True
- False