gt_mesh_paths:
- "/media/cs533r/data_b/data/3d/obj/armadillo.obj"
- "/media/cs533r/data_b/data/3d/obj/at-ot.obj"
- "/media/cs533r/data_b/data/3d/obj/engine.obj"
- "/media/cs533r/data_b/data/3d/obj/gear_shift.obj"
- "/media/cs533r/data_b/data/3d/obj/guangong.obj"
- "/media/cs533r/data_b/data/3d/obj/lion.obj"
- "/media/cs533r/data_b/data/3d/obj/ninjago_city.obj"
- "/media/cs533r/data_b/data/3d/obj/oak_tree.obj"

pred_mesh_paths:
  bacon:
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/bacon_default_multi_armadillo_4.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/bacon_default_multi_at-ot_4.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/bacon_default_multi_engine_4.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/bacon_default_multi_gear_shift_4.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/bacon_default_multi_guangong_4.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/bacon_default_multi_lion_4.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/bacon_default_multi_ninjago_city_4.obj"
  - "/media/cs533r/data_b/bacon_results/3d/bacon_default_multi/bacon_default_multi_oak_tree_4.obj"
  siren:
  - "/media/cs533r/data_b/siren_results/3d/default/armadillo.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/at-ot.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/engine.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/gear_shift.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/guangong.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/lion.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/ninjago_city.ply"
  - "/media/cs533r/data_b/siren_results/3d/default/oak_tree.ply"
  instant-ngp:
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/armadillo.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/at-ot.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/engine.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/gear_shift.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/guangong.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/lion.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/ninjago_city.ply"
  - "/media/cs533r/data_b/instant-ngp_results/3d/default/oak_tree.ply"

experiment_name: "bacon+siren+instant-ngp"

normalize: False

# chamfer/metro
num_points_to_sample: 100000

# chamfer
metric: "l2"
square_distances: False

# f-score
cube_side_length: 1.0
cube_side_factor: 2000

# iou
scale: 1