gt_mesh_paths:
- "/media/cs533r/data_b/normalized_GT_3D_shapes/obj/airplane.obj"
- "/media/cs533r/data_b/normalized_GT_3D_shapes/obj/bimba.obj"

pred_mesh_paths:
  instantngp:
    - "/media/cs533r/data_b/533R_results_1/3d_shapes/instantngp/airplane_hashgrid.obj"
    - "/media/cs533r/data_b/533R_results_1/3d_shapes/instantngp/bimba_hashgrid.obj"
  ldif:
    - "/media/cs533r/data_b/533R_results_1/3d_shapes/ldif/airplane.ply"
    - "/media/cs533r/data_b/533R_results_1/3d_shapes/ldif/bimba.ply"

experiment_name: "test"

normalize: True

# chamfer/metro
num_points_to_sample: 100000

# chamfer
metric: "l2"
square_distances: False

# f-score
cube_side_length: 1.0
cube_side_factor: 2000

# iou
scale: 1