img_paths:
- "/media/cs533r/data_b/zhijie/AB_test_nips/knn/images/patch_pos=354+361_size=300+200_gt.png"
- "/media/cs533r/data_b/zhijie/AB_test_nips/knn/images/patch_pos=354+361_size=300+200_k=1.png"
- "/media/cs533r/data_b/zhijie/AB_test_nips/knn/images/patch_pos=354+361_size=300+200_k=4.png"
- "/media/cs533r/data_b/zhijie/AB_test_nips/knn/images/patch_pos=354+361_size=300+200_k=8.png"
- "/media/cs533r/data_b/zhijie/AB_test_nips/knn/images/patch_pos=354+361_size=300+200_k=12.png"
- "/media/cs533r/data_b/zhijie/AB_test_nips/knn/images/patch_pos=354+361_size=300+200_k=16.png"

"exp_names":
- "GT"
- "K=1"
- "K=4"
- "K=8"
- "K=12"
- "K=16"

"hparam_name": "K"
"hparams":
- 1
- 4
- 8
- 12
- 16

"plot_type": "bar"

"x_max": 20
"y_min_psnr": 21.0
"y_max_psnr": 21.4
"y_min_ssim": 0.590
"y_max_ssim": 0.650

"bar_width": 0.8
"color_psnr": "firebrick"
"color_ssim": "midnightblue"

"show_x_label": False
"show_y_label": False

"width": 1800
"height": 2000

"plot_filepath": "knn_small_metrics_bar.png"
