img_paths:
- "/media/cs533r/data_b/zhijie/AB_test_nips/pri_num/images/patch_pos=968+201_size=300+200_gt.png"
- "/media/cs533r/data_b/zhijie/AB_test_nips/pri_num/images/patch_pos=968+201_size=300+200_5_1316.png"
- "/media/cs533r/data_b/zhijie/AB_test_nips/pri_num/images/patch_pos=968+201_size=300+200_4_5000.png"
- "/media/cs533r/data_b/zhijie/AB_test_nips/pri_num/images/patch_pos=968+201_size=300+200_3_13400.png"
- "/media/cs533r/data_b/zhijie/AB_test_nips/pri_num/images/patch_pos=968+201_size=300+200_2_21600.png"
- "/media/cs533r/data_b/zhijie/AB_test_nips/pri_num/images/patch_pos=968+201_size=300+200_1_25088.png"

"exp_names":
- "GT"
- "1300"
- "5000"
- "13000"
- "22000"
- "25000"

"hparam_name": "Num. Primitives"
"hparams":
- "1.3k"
- "5k"
- "13k"
- "22k"
- "25k"

"plot_type": "bar"

"x_max": 30000
"y_min_psnr": 18.5
"y_max_psnr": 20.0
"y_min_ssim": 0.525
"y_max_ssim": 0.7

"bar_width": 0.8
"color_psnr": "firebrick"
"color_ssim": "midnightblue"

"show_x_label": False
"show_y_label": False

"width": 1800
"height": 2000

"plot_filepath": "num_prims_small_metrics_bar.png"